security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/compte, roles: ROLE_USER }
        - { path: ^/message, roles: ROLE_USER }
        - { path: ^/paiement, roles: ROLE_USER }
        - { path: ^/commande, roles: ROLE_USER }
        - { path: ^/formation/\d+/candidature, roles: ROLE_USER }
        - { path: ^/formation/\d+/evaluer, roles: ROLE_USER }
        - { path: ^/new-cvtheque, roles: ROLE_USER }
        - { path: ^/emploi/\d+/candidature, roles: ROLE_USER }
        - { path: ^/stats, roles: [ROLE_STATS, ROLE_ADMIN] }
        - { path: ^/paiement, roles: [ROLE_FORMATEUR, ROLE_EMPLOYEUR, ROLE_ADMIN] }
        - { path: ^/new-formation, roles: [ROLE_FORMATEUR_VALIDE, ROLE_ADMIN] }
        - { path: ^/new-emploi, roles: [ROLE_EMPLOYEUR_1, ROLE_EMPLOYEUR_5, ROLE_EMPLOYEUR_10, ROLE_EMPLOYEUR_ILLIMITE, ROLE_ADMIN] }
